# Generated by Django 5.1.3 on 2025-02-17 00:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VetClinic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='VetClinicContacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook', models.URLField(blank=True, null=True)),
                ('instagram', models.URLField(blank=True, null=True)),
                ('gmail', models.EmailField(blank=True, max_length=254, null=True)),
                ('contact_number', models.CharField(blank=True, max_length=20, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('viber', models.CharField(blank=True, max_length=20, null=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='api.vetclinic')),
            ],
        ),
        migrations.CreateModel(
            name='VetClinicInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=15, max_digits=18)),
                ('longitude', models.DecimalField(decimal_places=15, max_digits=18)),
                ('address', models.TextField()),
                ('availability', models.CharField(max_length=255)),
                ('regular_hours', models.CharField(max_length=100)),
                ('emergency_hours', models.CharField(max_length=100)),
                ('vetId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='info', to='api.vetclinic')),
            ],
        ),
    ]
