# Generated by Django 5.1.3 on 2025-02-17 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vetcliniccontacts',
            old_name='clinic',
            new_name='vetId',
        ),
    ]
