# Generated by Django 5.1.3 on 2025-02-17 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_clinic_vetcliniccontacts_vetid'),
    ]

    operations = [
        migrations.CreateModel(
            name='DogDisease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='DogSymptoms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('question', models.TextField()),
                ('question_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='DogDiseaseFindings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity', models.CharField(max_length=50)),
                ('disease_description', models.TextField()),
                ('diseaseId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='api.dogdisease')),
            ],
        ),
        migrations.CreateModel(
            name='DogDiseaseFirstAid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstAid', models.TextField()),
                ('diseaseId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first_aid', to='api.dogdisease')),
            ],
        ),
    ]
