# Generated by Django 5.1.3 on 2025-02-18 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_dogdisease_dogsymptoms_dogdiseasefindings_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectedS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connectedId', models.TextField()),
                ('symptomsId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connection', to='api.dogsymptoms')),
            ],
        ),
    ]
