# Generated by Django 5.1.3 on 2025-02-20 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_connecteds'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dogdiseasefindings',
            name='diseaseId',
        ),
        migrations.AddField(
            model_name='dogdiseasefindings',
            name='name',
            field=models.CharField(default='Unknown Disease', max_length=255),
        ),
    ]
