# Generated by Django 5.1.3 on 2025-02-20 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_dogdiseasefindings_diseaseid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dogdiseasefirstaid',
            name='diseaseId',
        ),
        migrations.AddField(
            model_name='dogdiseasefirstaid',
            name='name',
            field=models.CharField(default='Unknown Disease', max_length=255),
        ),
    ]
