# Generated by Django 5.1.6 on 2025-04-08 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_dogdiseasefirstaid_diseaseid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dogsymptoms',
            name='common',
            field=models.BooleanField(default=False),
        ),
    ]
