# Generated by Django 5.1.6 on 2025-04-12 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_dogsymptoms_common'),
    ]

    operations = [
        migrations.AddField(
            model_name='dogdiseasefindings',
            name='specialization',
            field=models.TextField(default='[]'),
        ),
    ]
